import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Idas sommar honung",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#fae588] min-h-screen flex flex-col items-center justify-center">
          <header className="w-full bg-[#fdf8e1] py-4 shadow-md absolute top-0">
            <div className="max-w-5xl mx-auto flex items-center justify-between px-4 sm:px-6 md:px-8">
              <Link href="/" className="text-3xl font-bold text-gray-900">
                <img src="/images/logo.png" alt="Idas Sommarhonung" className="h-12" />
              </Link>
              <nav className="space-x-6">
                <Link href="/" className="text-lg text-gray-900 hover:text-yellow-700 transition-all">
                  Hem
                </Link>
                <Link href="/honung" className="text-lg text-gray-900 hover:text-yellow-700 transition-all">
                  Honung
                </Link>
                <Link href="/om-oss" className="text-lg text-gray-900 hover:text-yellow-700 transition-all">
                  Om oss
                </Link>
              </nav>
            </div>
          </header>

          {children}
          <footer className="w-full max-w-5xl py-8 text-center text-gray-600">
            © 2025 Idas Sommarhonung - Alla rättigheter reserverade
          </footer>
        </div>
      </body>
    </html>
  );
}
